// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build ios
// +build ios

package vfs

import (
	"errors"
	"fmt"
	"path/filepath"
	"unsafe"
)

/*
#cgo CFLAGS: -x objective-c
#cgo LDFLAGS: -framework Foundation

#import <Foundation/NSPathUtilities.h>
#import <Foundation/NSString.h>

#include <stdlib.h>
#include <string.h>

const char *app_support_path() {
	NSArray<NSString *> *paths = NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, YES);
	if ([paths count] < 1) {
		return NULL;
	}
	NSString *path = [paths firstObject];
	if (path == nil) {
		return NULL;
	}
	const char *data = [path UTF8String];
	if (data == NULL) {
		return NULL;
	}
	return strdup(data);
}
*/
import "C"

var (
	appSupportPath string
)

func pathForReadRaw(kind StateKind, name string) (string, error) {
	return pathForWrite(kind, name)
}

func pathForWriteRaw(kind StateKind, name string) (string, error) {
	// NOTE: These paths match those generated by state_file_xdg.go on macOS.
	// However, state_file_xdg.go relies on $HOME and which doesn't seem to be documented for iOS.
	// Consider migrating macOS support to here too, thus reducing amount of code involved.
	if appSupportPath == "" {
		appSupportPathCStr := C.app_support_path()
		if appSupportPathCStr == nil {
			return "", errors.New("could not find documents path")
		}
		defer C.free(unsafe.Pointer(appSupportPathCStr))
		appSupportPath = C.GoString(appSupportPathCStr)
	}
	switch kind {
	case Config:
		return filepath.Join(appSupportPath, "AAAAXY", name), nil
	case SavedGames:
		return filepath.Join(appSupportPath, "AAAAXY", name), nil
	default:
		return "", fmt.Errorf("searched for unsupported state kind: %d", kind)
	}
}
