name: aaaaxy
title: AAAAXY
base: core22
# contact: divVerent@gmail.com
# issues: https://github.com/divVerent/aaaaxy/issues
# source-code: https://github.com/divVerent/aaaaxy
# website: https://divVerent.github.io/aaaaxy
summary: A nonlinear puzzle platformer taking place in impossible spaces.
description: |
  AAAAXY is a nonlinear puzzle platformer taking place in impossible spaces.

  Although your general goal is reaching the surprising end of the game,
  you are encouraged to set your own goals while playing. Exploration will
  be rewarded, and secrets await you!

  So jump and run around, and enjoy losing your sense of orientation in
  this World of Wicked Weirdness. Find out what Van Vlijmen will make you
  do. Pick a path, get inside a Klein Bottle, recognize some memes, and by
  all means: don't look up.

  And beware of a minor amount of trolling.

  NOTE: to enable joystick/gamepad support, run:
  sudo snap connect aaaaxy:joystick
type: app
confinement: strict
icon: aaaaxy.svg
license: Apache-2.0
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

adopt-info: part-aaaaxy

parts:
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad

  keep-xdg:
    after:
      - desktop-glib-only
    plugin: dump
    source: .
    source-subdir: snap/keep-xdg

  part-aaaaxy:
    after:
      - desktop-glib-only
      - alsa-mixin
      - keep-xdg
    plugin: go
    build-snaps:
      - go
    build-environment:
      - GOTOOLCHAIN: local
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(sh scripts/version.sh semver)"
    override-build: |
      make BINARY="${SNAPCRAFT_PART_INSTALL}/bin/aaaaxy" BUILDTYPE=release
    source: https://github.com/divVerent/aaaaxy
    source-type: git
    build-packages:
      - advancecomp
      - libasound2-dev
      - libgl-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev
      - pkgconf
      - strip-nondeterminism
      - zip
    stage-packages:
      - libasound2
      - libgl1
      - libx11-6
      - libxau6

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm

environment:
  ALWAYS_USE_PULSEAUDIO: '1'

apps:
  aaaaxy:
    command-chain:
      # Support XDG variables.
      - bin/desktop-launch
      # Keep config and savegames across updates.
      - bin/keep-xdg
      # Support ALSA.
      - snap/command-chain/alsa-launch
    command: bin/aaaaxy
    plugs:
      - audio-playback
      - joystick
      - opengl
      - x11
