name: 100% Single-Platform Test Run
'on':
  pull_request: null
  push: null
  schedule:
    - cron: 29 12 * * *
  workflow_dispatch: null
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get -y install libasound2-dev libgl-dev
          libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev strip-nondeterminism
          xvfb
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Build
        run: make BUILDTYPE=fsrelease
        env:
          AAAAXY_BUILD_USE_VERSION_FILE: true
          GOTOOLCHAIN: local
      - name: Test
        run: 'xvfb-run scripts/github-action-benchmark.sh "100% linux-amd64" benchmark.txt
          scripts/regression-test-demo.sh linux-amd64 "your time: 1:19:13\\.866; your
          speedrun categories: 100%, All Notes and All Paths; try next: All Secrets\\."
          "./aaaaxy -debug_log_entity_defaults" assets/demos/_100percent_*.dem'
      - name: Archive Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: regression-test-results-100percent-linux-amd64
          path: 'assets/demos/*.dem.*.log

            assets/demos/*.dem.*.png

            '
      - name: Store Benchmark result
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
          (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
          || github.event_name == 'schedule' }}
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: 100% linux-amd64
          tool: customSmallerIsBetter
          output-file-path: benchmark.txt
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: dev/bench
          auto-push: false
          alert-threshold: 115%
          alert-comment-cc-users: '@divVerent'
          max-items-in-chart: 90
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Diff Benchmark Commit
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
          (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
          || github.event_name == 'schedule' }}
        run: |
          git show gh-pages > bench.patch
      - name: Upload Benchmark Results
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
          (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
          || github.event_name == 'schedule' }}
        uses: actions/upload-artifact@v7
        with:
          name: bench-100percent
          path: bench.patch
          if-no-files-found: error
  upload-results:
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name
      == 'workflow_dispatch' && github.ref == 'refs/heads/main') || github.event_name
      == 'schedule' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          ref: gh-pages
      - name: Clean Up
        run: |
          rm -f bench-*
      - name: Download Results
        uses: actions/download-artifact@v8
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Add Results
        run: |
          git apply bench-*/*.patch
      - name: Commit and Push
        run: |
          git commit -a -m"Update go-100percent benchmark results for commit ${GITHUB_SHA}."
          git push
